export const RESULT_TEXTS = {
  January: {
    AAA: { title: '「座っている時間」をできるだけ短くする', body: '説明テキスト' },
    AAB: { title: '「座っている時間」をできるだけ短くするB', body: '説明テキストB' },
    ABA: { title: 'ABA title', body: 'ABA body' },
    ABB: { title: 'ABB title', body: 'ABB body' },
    BAA: { title: 'BAA title', body: 'BAA body' },
    BAB: { title: 'BAB title', body: 'BAB body' },
    BBA: { title: 'BBA title', body: 'BBA body' },
    BBB: { title: 'BBB title', body: 'BBB body' },
  },
  February: {
    AAA: { title: '「座っている時間」をできるだけ短くする', body: '説明テキスト' },
    AAB: { title: '「座っている時間」をできるだけ短くするB', body: '説明テキストB' },
    ABA: { title: 'ABA title', body: 'ABA body' },
    ABB: { title: 'ABB title', body: 'ABB body' },
    BAA: { title: 'BAA title', body: 'BAA body' },
    BAB: { title: 'BAB title', body: 'BAB body' },
    BBA: { title: 'BBA title', body: 'BBA body' },
    BBB: { title: 'BBB title', body: 'BBB body' },
  },
  March: {
    AAA: { title: '「座っている時間」をできるだけ短くする', body: '説明テキスト' },
    AAB: { title: '「座っている時間」をできるだけ短くするB', body: '説明テキストB' },
    ABA: { title: 'ABA title', body: 'ABA body' },
    ABB: { title: 'ABB title', body: 'ABB body' },
    BAA: { title: 'BAA title', body: 'BAA body' },
    BAB: { title: 'BAB title', body: 'BAB body' },
    BBA: { title: 'BBA title', body: 'BBA body' },
    BBB: { title: 'BBB title', body: 'BBB body' },
  },
  April: {
    AAA: { title: '4月「座っている時間」をできるだけ短くする', body: '説明テキスト' },
    AAB: { title: '「座っている時間」をできるだけ短くするB', body: '説明テキストB' },
    ABA: { title: 'ABA title', body: 'ABA body' },
    ABB: { title: 'ABB title', body: 'ABB body' },
    BAA: { title: 'BAA title', body: 'BAA body' },
    BAB: { title: 'BAB title', body: 'BAB body' },
    BBA: { title: 'BBA title', body: 'BBA body' },
    BBB: { title: 'BBB title', body: 'BBB body' },
  },
  May: {
    AAA: { title: '「座っている時間」をできるだけ短くする', body: '説明テキスト' },
    AAB: { title: '「座っている時間」をできるだけ短くするB', body: '説明テキストB' },
    ABA: { title: 'ABA title', body: 'ABA body' },
    ABB: { title: 'ABB title', body: 'ABB body' },
    BAA: { title: 'BAA title', body: 'BAA body' },
    BAB: { title: 'BAB title', body: 'BAB body' },
    BBA: { title: 'BBA title', body: 'BBA body' },
    BBB: { title: 'BBB title', body: 'BBB body' },
  },
  June: {
    AAA: { title: '「座っている時間」をできるだけ短くする', body: '説明テキスト' },
    AAB: { title: '「座っている時間」をできるだけ短くするB', body: '説明テキストB' },
    ABA: { title: 'ABA title', body: 'ABA body' },
    ABB: { title: 'ABB title', body: 'ABB body' },
    BAA: { title: 'BAA title', body: 'BAA body' },
    BAB: { title: 'BAB title', body: 'BAB body' },
    BBA: { title: 'BBA title', body: 'BBA body' },
    BBB: { title: 'BBB title', body: 'BBB body' },
  },
  July: {
    AAA: { title: '「座っている時間」をできるだけ短くする', body: '説明テキスト' },
    AAB: { title: '「座っている時間」をできるだけ短くするB', body: '説明テキストB' },
    ABA: { title: 'ABA title', body: 'ABA body' },
    ABB: { title: 'ABB title', body: 'ABB body' },
    BAA: { title: 'BAA title', body: 'BAA body' },
    BAB: { title: 'BAB title', body: 'BAB body' },
    BBA: { title: 'BBA title', body: 'BBA body' },
    BBB: { title: 'BBB title', body: 'BBB body' },
  },
  August: {
    AAA: { title: '「座っている時間」をできるだけ短くする', body: '説明テキスト' },
    AAB: { title: '「座っている時間」をできるだけ短くするB', body: '説明テキストB' },
    ABA: { title: 'ABA title', body: 'ABA body' },
    ABB: { title: 'ABB title', body: 'ABB body' },
    BAA: { title: 'BAA title', body: 'BAA body' },
    BAB: { title: 'BAB title', body: 'BAB body' },
    BBA: { title: 'BBA title', body: 'BBA body' },
    BBB: { title: 'BBB title', body: 'BBB body' },
  },
  September: {
    AAA: { title: '「座っている時間」をできるだけ短くする', body: '説明テキスト' },
    AAB: { title: '「座っている時間」をできるだけ短くするB', body: '説明テキストB' },
    ABA: { title: 'ABA title', body: 'ABA body' },
    ABB: { title: 'ABB title', body: 'ABB body' },
    BAA: { title: 'BAA title', body: 'BAA body' },
    BAB: { title: 'BAB title', body: 'BAB body' },
    BBA: { title: 'BBA title', body: 'BBA body' },
    BBB: { title: 'BBB title', body: 'BBB body' },
  },
  October: {
    AAA: { title: '「座っている時間」をできるだけ短くする', body: '説明テキスト' },
    AAB: { title: '「座っている時間」をできるだけ短くするB', body: '説明テキストB' },
    ABA: { title: 'ABA title', body: 'ABA body' },
    ABB: { title: 'ABB title', body: 'ABB body' },
    BAA: { title: 'BAA title', body: 'BAA body' },
    BAB: { title: 'BAB title', body: 'BAB body' },
    BBA: { title: 'BBA title', body: 'BBA body' },
    BBB: { title: 'BBB title', body: 'BBB body' },
  },
  November: {
    AAA: { title: '「座っている時間」をできるだけ短くする', body: '説明テキスト' },
    AAB: { title: '「座っている時間」をできるだけ短くするB', body: '説明テキストB' },
    ABA: { title: 'ABA title', body: 'ABA body' },
    ABB: { title: 'ABB title', body: 'ABB body' },
    BAA: { title: 'BAA title', body: 'BAA body' },
    BAB: { title: 'BAB title', body: 'BAB body' },
    BBA: { title: 'BBA title', body: 'BBA body' },
    BBB: { title: 'BBB title', body: 'BBB body' },
  },
  December: {
    AAA: { title: '「座っている時間」をできるだけ短くする', body: '説明テキスト' },
    AAB: { title: '「座っている時間」をできるだけ短くするB', body: '説明テキストB' },
    ABA: { title: 'ABA title', body: 'ABA body' },
    ABB: { title: 'ABB title', body: 'ABB body' },
    BAA: { title: 'BAA title', body: 'BAA body' },
    BAB: { title: 'BAB title', body: 'BAB body' },
    BBA: { title: 'BBA title', body: 'BBA body' },
    BBB: { title: 'BBB title', body: 'BBB body' },
  },
}
